### ISSUE TITLE
'ru.livetex.sdkui.chat.AddFileActions' is not public in 'ru.livetex.sdkui.chat'. Cannot be accessed from outside package

### ISSUE THREAD

**Issue by QuarK264** [LiveTex/sdk-ui-android#26]
Добрый день,

Обновил библиотеку с версии 1.1.8 до 1.2.7, в новой версии изменился метод `AddFileDialog.attach()`. Теперь он вместо `Context` принимает `AddFileActions`, этот интерфейс определён в `AddFileDialog.java` как `interface AddFileActions` из-за чего при попытке его реализации выдаёт ошибку:

> 'ru.livetex.sdkui.chat.AddFileActions' is not public in 'ru.livetex.sdkui.chat'. Cannot be accessed from outside package

Не очень понял почему выдаёт такую ошибку, потому что интерфейс по умолчанию должен быть `public` (гугл так же считает). Можно ли сделать интерфейс публичным в библиотеке?

Кроме этой есть похожая проблема с доступностью метода `requestCamera()` из класса `AddFileDialog`. Пример реализации работы с камерой из файла `ChatActivity.java` из demo-lib выдаёт ошибку:

> 'requestCamera(android.app.Activity)' is not public in 'ru.livetex.sdkui.chat.AddFileDialog'. Cannot be accessed from outside package

**Comment by maxxx** [comment]
Спасибо, недоглядел. Попробуй версию 1.2.8, должно быть исправлено

**Comment by QuarK264** [comment]
Обновился, теперь проблем с камерой нет, спасибо
