### ISSUE TITLE
Неправильное выравнивание текста в диалоге добавления файла

### ISSUE THREAD

**Issue by QuarK264** [LiveTex/sdk-ui-android#29]
Добрый день,

В библиотеке версии 1.2.8 (и более ранних), на диалоге добавления файла съехало выравнивание текста кнопки "Отменить". Пример на скриншоте ниже

<img src="https://user-images.githubusercontent.com/9616488/211821724-692db299-12cc-48d8-b748-4ef9ace4b864.png" width="300"/>

Понимаю, что ошибка весьма странная, поскольку на превью текст отображается по центру как ожидается. Но при использовании библиотеки на двух разных телефонах текст кнопки съезжает с центра к левому краю. Посмотрите, пожалуйста, может быть удастся решить проблему явным указанием выравнивания текста по центру

**Comment by maxxx** [comment]
https://github.com/LiveTex/sdk-ui-android/commit/5ca7a6419ee76ec9753d4a096dad6ef53c842412
должно помочь
